# Stage 1: Build React Frontend
FROM node:20-alpine AS builder

WORKDIR /app
COPY . .

ARG VITE_API_URL
ARG COOKIE_NAME
ENV VITE_API_URL=$VITE_API_URL
ENV COOKIE_NAME=$COOKIE_NAME

RUN npm install
RUN npm run build --workspace=client

# Stage 2: NGINX Serve
FROM nginx:alpine

COPY --from=builder /app/apps/client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
