name: Build Frontend & Backend Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Frontend Docker Image
        run: |
          docker build \
            --file Dockerfile.frontend \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            --build-arg COOKIE_NAME=${{ secrets.COOKIE_NAME }} \
            -t ra41aa/eg-auth:frontend .

      - name: Build Backend Docker Image
        run: |
          docker build \
            --file Dockerfile.backend \
            --build-arg COOKIE_NAME=${{ secrets.COOKIE_NAME }} \
            --build-arg BACKEND_PORT=${{ secrets.BACKEND_PORT }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} \
            --build-arg MONGODB_CONN_STRING=${{ secrets.MONGODB_CONN_STRING }} \
            --build-arg JWT_EXP_TIME=${{ secrets.JWT_EXP_TIME }} \
            --build-arg CORS_ORIGIN=${{ secrets.CORS_ORIGIN }} \
            -t ra41aa/eg-auth:backend .
